#!/bin/zsh
# GitHub Auto-PR Creator
# Automatically creates PRs for completed work

WORKSPACE="/Users/mohlt/.openclaw/workspace"
REPO="mohltbot/mission-control"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if we're in a git repo
cd "$WORKSPACE"

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    log_error "Not a git repository"
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git branch --show-current)

# Don't create PRs from main
if [[ "$CURRENT_BRANCH" == "main" ]]; then
    log_warn "Currently on main branch. Switch to a feature branch to create PR."
    
    # Check if there are uncommitted changes
    if ! git diff --quiet HEAD; then
        log_info "Uncommitted changes detected on main."
        read -p "Create a feature branch and commit changes? (y/n) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            read -p "Enter feature branch name (e.g., feature/my-update): " BRANCH_NAME
            git checkout -b "$BRANCH_NAME"
            CURRENT_BRANCH="$BRANCH_NAME"
        else
            exit 0
        fi
    else
        exit 0
    fi
fi

# Check if there are changes to commit
if git diff --quiet HEAD; then
    log_warn "No changes to commit on branch $CURRENT_BRANCH"
    exit 0
fi

# Get commit message
log_info "Changes detected on branch: $CURRENT_BRANCH"
echo ""
echo "Recent changes:"
git diff --stat HEAD
echo ""

# Auto-generate commit message from changes
AUTO_MESSAGE=$(git diff --name-only HEAD | head -5 | tr '\n' ', ' | sed 's/, $//')
if [[ -z "$AUTO_MESSAGE" ]]; then
    AUTO_MESSAGE="Update files"
fi

read -p "Commit message [$AUTO_MESSAGE]: " COMMIT_MESSAGE
COMMIT_MESSAGE=${COMMIT_MESSAGE:-$AUTO_MESSAGE}

# Commit changes
git add .
git commit -m "$COMMIT_MESSAGE"
log_info "Committed: $COMMIT_MESSAGE"

# Push branch
git push -u origin "$CURRENT_BRANCH"
log_info "Pushed to origin/$CURRENT_BRANCH"

# Check if PR already exists
EXISTING_PR=$(gh pr list --head "$CURRENT_BRANCH" --json number --jq '.[0].number')

if [[ -n "$EXISTING_PR" ]]; then
    log_info "PR already exists: #$EXISTING_PR"
    gh pr view "$EXISTING_PR" --web
    exit 0
fi

# Generate PR description
log_info "Generating PR description..."

# Get recent commits for PR body
COMMIT_LOG=$(git log main.."$CURRENT_BRANCH" --oneline --no-decorate | head -10)

# Get changed files
CHANGED_FILES=$(git diff --name-status main..."$CURRENT_BRANCH" | head -20)

# Create PR description
PR_BODY=$(cat << EOF
## Summary
$COMMIT_MESSAGE

## Changes
$(echo "$CHANGED_FILES" | awk '{print "- " $0}')

## Commits
$(echo "$COMMIT_LOG" | awk '{print "- " $0}')

## Testing
- [ ] Tested locally
- [ ] All checks passing

---
*Auto-generated by OpenClaw GitHub Auto-PR*
EOF
)

# Create PR
log_info "Creating PR..."
PR_URL=$(gh pr create \
    --title "$COMMIT_MESSAGE" \
    --body "$PR_BODY" \
    --base main \
    --head "$CURRENT_BRANCH" \
    2>&1)

if [[ $? -eq 0 ]]; then
    log_info "✅ PR created successfully!"
    echo "$PR_URL"
    
    # Post to Discord
    if command -v openclaw &> /dev/null; then
        MESSAGE="🚀 New PR ready for review: $COMMIT_MESSAGE

$PR_URL"
        
        # This would integrate with your Discord bot
        echo "Discord notification: $MESSAGE"
    fi
else
    log_error "Failed to create PR:"
    echo "$PR_URL"
    exit 1
fi
